name: 'Build & Test'
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt update -y && sudo apt install -y libfuse3-dev cmake g++
      - uses: actions/checkout@v3
      - run: scripts/test.sh
